spring.application.name=quiz
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/quizquestion
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl.auto=udpate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.data-source-properties.serverTimezone=Asia/Kathmandu